@baseUrl = http://localhost:3000

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@localhost",
  "password": "john.doe"
}

###

@access_token = {{login.response.body.access_token}}
@refresh_token = {{login.response.body.refresh_token}}

###

# @name check
GET {{baseUrl}}/auth/check
Authorization: Bearer {{access_token}}

###

# @name logout
GET {{baseUrl}}/auth/logout

###

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "abcdef@localhost",
  "password": "abcdef"
}

###

# @name jwtRefresh
GET {{baseUrl}}/auth/refresh
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh_token": "{{refresh_token}}"
}

###

@access_token = {{jwtRefresh.response.body.access_token}}
